<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>An Aspire hosting integration for configuring Litestream sidecars for SQLite replication.</Description>
    <AdditionalPackageTags>hosting litestream sqlite replication backup</AdditionalPackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CommunityToolkit.Aspire.Hosting.Litestream.Tests"></InternalsVisibleTo>
  </ItemGroup>
</Project>
