<Project Sdk="Aspire.AppHost.Sdk/13.2.0-preview.1.26152.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CommunityToolkit.Aspire.Hosting.Minio\CommunityToolkit.Aspire.Hosting.Minio.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\CommunityToolkit.Aspire.Litestream.Testing.Verifier\CommunityToolkit.Aspire.Litestream.Testing.Verifier.csproj" />
    <ProjectReference Include="..\CommunityToolkit.Aspire.Litestream.Testing.Writer\CommunityToolkit.Aspire.Litestream.Testing.Writer.csproj" />
  </ItemGroup>

</Project>
